"""empty message

Revision ID: add_project_tbl
Revises: 
Create Date: 2022-08-09 13:48:18.814861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_project_tbl'
down_revision = '21790837a3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pname', sa.String(length=255), nullable=False),
    sa.Column('sampling_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255)),
    sa.Column('instructions', sa.String(length=255)),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id')),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
