"""empty message

Revision ID: add_project_tbl
Revises: 
Create Date: 2022-08-09 13:48:18.814861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "alt_project_rnm_pname"
down_revision = "add_project_tbl"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "pname", nullable=False, new_column_name="project_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "project_name", nullable=False, new_column_name="pname")
    # ### end Alembic commands ###
